### ISSUE TITLE
ES6 support

### ISSUE THREAD

**Issue by haoxins** [weareoffsider/react-jade-transformer#3]
such as

``` js
class List extends React.Component{
  render() {
    return rj`
div
  span hello
`
  }
}
```

https://facebook.github.io/react/blog/2015/01/27/react-v0.13.0-beta-1.html

**Comment by MalucoMarinero** [comment]
The behaviour in ES6 shouldn't really change, as the transformer is not for creating classes, just outputting render calls, the above should already compile to:

```
class List extends React.Component{
  render() {
    return React.DOM.div({}, React.DOM.span({}, "hello"));
  }
}
```
